# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  TestFlight.takeOff('6b0ec22b109bdf447fa102d37a383273_OTE5MDAyMDEyLTA1LTIwIDE1OjQ4OjA2LjI5MjMzMQ')
  end)
end
